Update Jenkinsfile_agentes

diff --git a/Jenkinsfile_agentes b/Jenkinsfile_agentes
--- a/Jenkinsfile_agentes
+++ b/Jenkinsfile_agentes
@@ -66,6 +66,29 @@ pipeline {
                         }
                     }
                 }
+		stage ('Deploy'){
+		    agent { label 'AgenteAny'}
+	            steps{
+	                sh 'sam build'
+	                sh 'sam deploy --no-fail-on-empty-changeset || true --config-file samconfig.toml --config-env staging'
+	                //Obtenemos las urls del servicio desplegado en con sam
+	                script {
+			    def stageName = env.STAGE_NAME
+	                    echo "Stage: ${stageName}"
+	                    def nodeName = env.NODE_NAME
+	                    echo "Agent: ${nodeName}"
+	                    def stackInfo = sh(script: "aws cloudformation describe-stacks --stack-name ${STACK_NAME}", returnStdout: true).trim()
+	                    def output = readJSON(text: stackInfo)
+	                    def apiUrl = output.Stacks[0].Outputs.find { it.OutputKey == 'BaseUrlApi' }?.OutputValue
+	                    if (apiUrl) {
+	                        env.BASE_URL = apiUrl
+	                        echo "API URL: ${env.BASE_URL}"
+	                    } else {
+	                        error "API URL not found in stack outputs"
+	                    }
+	                }
+	            }
+        	}
 		stage('Tests Rest') {
 		  agent { label 'AgentCD'}
                   steps {
@@ -82,29 +105,7 @@ pipeline {
                                     '''
                            }
                         }
-            }
-            }
-        }
-        stage ('Deploy'){
-            steps{
-                sh 'sam build'
-                sh 'sam deploy --no-fail-on-empty-changeset || true --config-file samconfig.toml --config-env staging'
-                //Obtenemos las urls del servicio desplegado en con sam
-                script {
-		    def stageName = env.STAGE_NAME
-                    echo "Stage: ${stageName}"
-                    def nodeName = env.NODE_NAME
-                    echo "Agent: ${nodeName}"
-                    def stackInfo = sh(script: "aws cloudformation describe-stacks --stack-name ${STACK_NAME}", returnStdout: true).trim()
-                    def output = readJSON(text: stackInfo)
-                    def apiUrl = output.Stacks[0].Outputs.find { it.OutputKey == 'BaseUrlApi' }?.OutputValue
-                    if (apiUrl) {
-                        env.BASE_URL = apiUrl
-                        echo "API URL: ${env.BASE_URL}"
-                    } else {
-                        error "API URL not found in stack outputs"
-                    }
-                }
+            	}
             }
         }
             stage('Promote') {
